// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SKS_TitleMap","status":true,"description":"v1.03 Utilise une map en tant qu'écran-titre pour votre jeu.\r\nPeut-être un tutoriel dessus un jour","parameters":{"ID MAP TITLE":"1"}},
{"name":"SKS_Utils","status":true,"description":"v1.00 Script utilitaire.","parameters":{"textToQuit":"Back to Windows"}}
];
