// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SKE_Core","status":true,"description":"v1.0 Plugin principal pour le support des script SKE et SKS.\r\nRetrouvez les autres scripts sur GitHub. MV version : 1.5.1 !","parameters":{"gW":"","gameWinWidth":"1200","gameWinHeight":"720","launchDebugTool":"false"}},
{"name":"--------------------","status":false,"description":"------------------------------------------------------------","parameters":{}},
{"name":"SKS_TitleMap","status":true,"description":"v1.03 Utilise une map en tant qu'écran-titre pour votre jeu.\r\nPeut-être un tutoriel dessus un jour","parameters":{"ID MAP TITLE":"1"}},
{"name":"SKS_Utils","status":true,"description":"v1.00 Script utilitaire.","parameters":{"textToQuit":"Back to Windows"}}
];
